import jsPDF from 'jspdf';

/**
 * Export a quotation as a formatted PDF
 */
export const exportQuotationPDF = (quotation) => {
  const doc = new jsPDF();
  const margin = 20;
  let y = margin;

  // Header bar
  doc.setFillColor(0, 88, 190);
  doc.rect(0, 0, 210, 30, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('VendorPro', margin, 18);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Vendor Management & Quotation System', margin, 25);

  y = 40;
  doc.setTextColor(25, 28, 30);

  // RFQ ID + Title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(quotation.title, margin, y);
  y += 7;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(118, 119, 125);
  doc.text(`RFQ ID: ${quotation.rfqId}`, margin, y);
  y += 12;

  // Divider
  doc.setDrawColor(198, 198, 205);
  doc.line(margin, y, 210 - margin, y);
  y += 10;

  // Status badge
  doc.setTextColor(25, 28, 30);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Status:', margin, y);
  doc.setFont('helvetica', 'normal');
  doc.text(quotation.status.toUpperCase().replace('_', ' '), margin + 22, y);
  y += 10;

  // Vendor Info
  doc.setFont('helvetica', 'bold');
  doc.text('Vendor Information', margin, y);
  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const vendor = quotation.vendor;
  if (vendor) {
    doc.text(`Vendor Name: ${vendor.vendorName || '-'}`, margin, y); y += 6;
    doc.text(`Company: ${vendor.companyName || '-'}`, margin, y); y += 6;
    doc.text(`Email: ${vendor.email || '-'}`, margin, y); y += 6;
    doc.text(`Contact: ${vendor.contactNumber || '-'}`, margin, y); y += 6;
    doc.text(`Address: ${vendor.businessAddress || '-'}`, margin, y); y += 10;
  }

  // Divider
  doc.setDrawColor(198, 198, 205);
  doc.line(margin, y, 210 - margin, y);
  y += 10;

  // Quotation Details
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Quotation Details', margin, y); y += 7;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Description: ${quotation.description || '-'}`, margin, y, { maxWidth: 170 });
  y += doc.splitTextToSize(quotation.description || '-', 170).length * 5 + 4;
  doc.text(`Submission Date: ${quotation.submissionDate ? new Date(quotation.submissionDate).toLocaleDateString() : '-'}`, margin, y); y += 6;
  if (quotation.expirationDate) {
    doc.text(`Expiration Date: ${new Date(quotation.expirationDate).toLocaleDateString()}`, margin, y); y += 6;
  }

  // Amount highlight
  y += 4;
  doc.setFillColor(240, 244, 246);
  doc.roundedRect(margin, y, 170, 18, 3, 3, 'F');
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 88, 190);
  doc.text(
    `Quoted Amount: $${Number(quotation.amount).toLocaleString('en-US', { minimumFractionDigits: 2 })}`,
    margin + 6,
    y + 11
  );
  y += 26;

  // Footer
  doc.setTextColor(118, 119, 125);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by VendorPro on ${new Date().toLocaleString()}`, margin, 287);

  doc.save(`${quotation.rfqId || 'quotation'}.pdf`);
};
